# This file is used for local development overrides
# It automatically loads environment variables from .env file
# Copy .env.example to .env and fill in your values

version: '3.8'

services:
  deepthought:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    # Uncomment volumes for development with hot reload
    # volumes:
    #   - ./src:/app/src:ro
    #   - ./build:/app/build
    # Enable for development debugging
    # ports:
    #   - "9229:9229"  # Node.js debugging port
